name: Edian Comachio ESC
markdown: kramdown
highlighter: rouge # pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
baseurl: /portfolio/ 

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems: ['jekyll-seo-tag']

google_verify: Wv_NNL-kitScKcmTiw_KGnwLEI2cbuPqiPkNKQd-zlk