name: Your New Jekyll Site
markdown: kramdown
highlighter: rouge # pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
baseurl: /

kramdown:
  input: GFM
  syntax_highlighter: rouge
