name: Edian Comachio
markdown: kramdown
highlighter: rouge # pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
baseurl: /portfolio/ 

kramdown:
  input: GFM
  syntax_highlighter: rouge
